action: broken
packages:
- linux-64/herwig-7.2.0-ha34a05f_0.conda
- linux-64/herwig-7.2.0-hf971abe_1.conda
- linux-64/herwig-7.2.0-h2aa1e36_2.conda
- linux-64/herwig-7.2.0-h2aa1e36_3.conda
- linux-aarch64/herwig-7.2.0-hf3dcea7_3.conda
- osx-64/herwig-7.2.0-hccd5a3e_3.conda
- osx-arm64/herwig-7.2.0-h249e212_3.conda
- linux-64/herwig-7.3.0-h2aa1e36_0.conda
- linux-aarch64/herwig-7.3.0-hf3dcea7_0.conda
- osx-64/herwig-7.3.0-hccd5a3e_0.conda
- osx-arm64/herwig-7.3.0-h249e212_0.conda
