name: run
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Prevent multiple jobs running in parallel
      id: conversion_lock
      uses: beckermr/turnstyle-python@v1
      with:
        abort-after-seconds: 3
        poll-interval-seconds: 2
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - uses: actions/checkout@v2
      # outcome is evaluated before continue-on-error above
      if: steps.conversion_lock.outcome == 'success'

    - name: fast finish
      if: ${{ steps.conversion_lock.outcome == 'success' }}
      run: |
        set -x
        # avoid wasting CI time if there is nothing to do
        broken_count="$(ls broken/*.txt | grep -v broken/example.txt | wc -l)"
        not_broken_count="$(ls not_broken/*.txt | grep -v not_broken/example.txt | wc -l)"
        token_reset_count="$(ls token_reset/*.txt | grep -v token_reset/example.txt | wc -l)"
        if [[ "${broken_count}" == "0" && "${not_broken_count}" == "0" && "${token_reset_count}" == "0" ]]; then
          echo "nothing to do, setting ci skip!"
          echo "CI_SKIP=true" >> $GITHUB_ENV
        fi

    - uses: conda-incubator/setup-miniconda@v2
      if: steps.conversion_lock.outcome == 'success' && ! env.CI_SKIP
      with:
        activate-environment: cf
        environment-file: environment.yml
        auto-activate-base: true

    - name: mark packages as broken
      if: steps.conversion_lock.outcome == 'success' && ! env.CI_SKIP
      shell: bash -l {0}
      run: |
          conda activate cf
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python mark_broken.py mark
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}

    - name: reset feedstock tokens
      if: steps.conversion_lock.outcome == 'success' && ! env.CI_SKIP
      shell: bash -l {0}
      run: |
          conda activate cf
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          python token_reset.py reset
      env:
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}
        CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
        AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}

    - name: Push changes
      if: steps.conversion_lock.outcome == 'success' && ! env.CI_SKIP
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
